/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.linkedlist;

import org.junit.Test;

import com.cp.linkedlist.Node;

import static org.junit.Assert.*;

public class NodeTest {
    
}
